/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Attribute, attributeSchema } from '../models/attribute';
import { array, boolean, number, optional } from '../schema';
import { BaseController } from './baseController';

export class AttributesController extends BaseController {
  /**
   * Without params, it returns a list of Attributes the user has access to
   *
   * @param all      Can only be used by admins or managers to fetch all entities
   * @param userId   Standard users can use this only with their own _userId_
   * @param deviceId Standard users can use this only with _deviceId_s, they have access to
   * @param groupId  Standard users can use this only with _groupId_s, they have access to
   * @param refresh
   * @return Response from the API call
   */
  async fetchAListOfAttributes(
    all?: boolean,
    userId?: number,
    deviceId?: number,
    groupId?: number,
    refresh?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Attribute[]>> {
    const req = this.createRequest('GET', '/attributes/computed');
    const mapped = req.prepareArgs({
      all: [all, optional(boolean())],
      userId: [userId, optional(number())],
      deviceId: [deviceId, optional(number())],
      groupId: [groupId, optional(number())],
      refresh: [refresh, optional(boolean())],
    });
    req.query('all', mapped.all);
    req.query('userId', mapped.userId);
    req.query('deviceId', mapped.deviceId);
    req.query('groupId', mapped.groupId);
    req.query('refresh', mapped.refresh);
    return req.callAsJson(array(attributeSchema), requestOptions);
  }

  /**
   * Create an Attribute
   *
   * @param body
   * @return Response from the API call
   */
  async createAnAttribute(
    body: Attribute,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Attribute>> {
    const req = this.createRequest('POST', '/attributes/computed');
    const mapped = req.prepareArgs({ body: [body, attributeSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(attributeSchema, requestOptions);
  }

  /**
   * Update an Attribute
   *
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateAnAttribute(
    id: number,
    body: Attribute,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Attribute>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, attributeSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/attributes/computed/${mapped.id}`;
    return req.callAsJson(attributeSchema, requestOptions);
  }

  /**
   * Delete an Attribute
   *
   * @param id
   * @return Response from the API call
   */
  async deleteAnAttribute(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/attributes/computed/${mapped.id}`;
    return req.call(requestOptions);
  }
}
