/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Calendar, calendarSchema } from '../models/calendar';
import { array, boolean, number, optional } from '../schema';
import { BaseController } from './baseController';

export class CalendarsController extends BaseController {
  /**
   * Without params, it returns a list of Calendars the user has access to
   *
   * @param all    Can only be used by admins or managers to fetch all entities
   * @param userId Standard users can use this only with their own _userId_
   * @return Response from the API call
   */
  async fetchAListOfCalendars(
    all?: boolean,
    userId?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Calendar[]>> {
    const req = this.createRequest('GET', '/calendars');
    const mapped = req.prepareArgs({
      all: [all, optional(boolean())],
      userId: [userId, optional(number())],
    });
    req.query('all', mapped.all);
    req.query('userId', mapped.userId);
    return req.callAsJson(array(calendarSchema), requestOptions);
  }

  /**
   * Create a Calendar
   *
   * @param body
   * @return Response from the API call
   */
  async createACalendar(
    body: Calendar,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Calendar>> {
    const req = this.createRequest('POST', '/calendars');
    const mapped = req.prepareArgs({ body: [body, calendarSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(calendarSchema, requestOptions);
  }

  /**
   * Update a Calendar
   *
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateACalendar(
    id: number,
    body: Calendar,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Calendar>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, calendarSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/calendars/${mapped.id}`;
    return req.callAsJson(calendarSchema, requestOptions);
  }

  /**
   * Delete a Calendar
   *
   * @param id
   * @return Response from the API call
   */
  async deleteACalendar(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/calendars/${mapped.id}`;
    return req.call(requestOptions);
  }
}
