/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Event, eventSchema } from '../models/event';
import { number } from '../schema';
import { BaseController } from './baseController';

export class EventsController extends BaseController {
  /**
   * @param id
   * @return Response from the API call
   */
  async eventsByIdGET(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Event>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/events/${mapped.id}`;
    return req.callAsJson(eventSchema, requestOptions);
  }
}
