/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { Notification, notificationSchema } from '../models/notification';
import {
  NotificationType,
  notificationTypeSchema,
} from '../models/notificationType';
import { array, boolean, number, optional } from '../schema';
import { BaseController } from './baseController';

export class NotificationsController extends BaseController {
  /**
   * Without params, it returns a list of Notifications the user has access to
   *
   * @param all      Can only be used by admins or managers to fetch all entities
   * @param userId   Standard users can use this only with their own _userId_
   * @param deviceId Standard users can use this only with _deviceId_s, they have access to
   * @param groupId  Standard users can use this only with _groupId_s, they have access to
   * @param refresh
   * @return Response from the API call
   */
  async fetchAListOfNotifications(
    all?: boolean,
    userId?: number,
    deviceId?: number,
    groupId?: number,
    refresh?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Notification[]>> {
    const req = this.createRequest('GET', '/notifications');
    const mapped = req.prepareArgs({
      all: [all, optional(boolean())],
      userId: [userId, optional(number())],
      deviceId: [deviceId, optional(number())],
      groupId: [groupId, optional(number())],
      refresh: [refresh, optional(boolean())],
    });
    req.query('all', mapped.all);
    req.query('userId', mapped.userId);
    req.query('deviceId', mapped.deviceId);
    req.query('groupId', mapped.groupId);
    req.query('refresh', mapped.refresh);
    return req.callAsJson(array(notificationSchema), requestOptions);
  }

  /**
   * Create a Notification
   *
   * @param body
   * @return Response from the API call
   */
  async createANotification(
    body: Notification,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Notification>> {
    const req = this.createRequest('POST', '/notifications');
    const mapped = req.prepareArgs({ body: [body, notificationSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(notificationSchema, requestOptions);
  }

  /**
   * Update a Notification
   *
   * @param id
   * @param body
   * @return Response from the API call
   */
  async updateANotification(
    id: number,
    body: Notification,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Notification>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      id: [id, number()],
      body: [body, notificationSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/notifications/${mapped.id}`;
    return req.callAsJson(notificationSchema, requestOptions);
  }

  /**
   * Delete a Notification
   *
   * @param id
   * @return Response from the API call
   */
  async deleteANotification(
    id: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ id: [id, number()] });
    req.appendTemplatePath`/notifications/${mapped.id}`;
    return req.call(requestOptions);
  }

  /**
   * Fetch a list of available Notification types
   *
   * @return Response from the API call
   */
  async fetchAListOfAvailableNotificationTypes(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<NotificationType[]>> {
    const req = this.createRequest('GET', '/notifications/types');
    return req.callAsJson(array(notificationTypeSchema), requestOptions);
  }

  /**
   * Send test notification to current user via Email and SMS
   *
   * @return Response from the API call
   */
  async sendTestNotificationToCurrentUserViaEmailAndSMS(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/notifications/test');
    req.throwOn(400, ApiError, 'Could happen if sending has failed');
    return req.call(requestOptions);
  }
}
