/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '@apimatic/core';
import { ApiResponse, RequestOptions } from '../core';
import { Permission, permissionSchema } from '../models/permission';
import { BaseController } from './baseController';

export class PermissionsController extends BaseController {
  /**
   * Link an Object to another Object
   *
   * @param body
   * @return Response from the API call
   */
  async linkAnObjectToAnotherObject(
    body: Permission,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/permissions');
    const mapped = req.prepareArgs({ body: [body, permissionSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'No permission');
    return req.call(requestOptions);
  }

  /**
   * Unlink an Object from another Object
   *
   * @return Response from the API call
   */
  async unlinkAnObjectFromAnotherObject(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE', '/permissions');
    return req.call(requestOptions);
  }
}
