/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Server, serverSchema } from '../models/server';
import { BaseController } from './baseController';

export class ServerController extends BaseController {
  /**
   * Fetch Server information
   *
   * @return Response from the API call
   */
  async fetchServerInformation(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Server>> {
    const req = this.createRequest('GET', '/server');
    return req.callAsJson(serverSchema, requestOptions);
  }

  /**
   * Update Server information
   *
   * @param body
   * @return Response from the API call
   */
  async updateServerInformation(
    body: Server,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Server>> {
    const req = this.createRequest('PUT', '/server');
    const mapped = req.prepareArgs({ body: [body, serverSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    return req.callAsJson(serverSchema, requestOptions);
  }
}
