/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { Statistics, statisticsSchema } from '../models/statistics';
import { array, string } from '../schema';
import { BaseController } from './baseController';

export class StatisticsController extends BaseController {
  /**
   * Fetch server Statistics
   *
   * @param from in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
   * @param to   in IS0 8601 format. eg. `1963-11-22T18:30:00Z`
   * @return Response from the API call
   */
  async fetchServerStatistics(
    from: string,
    to: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Statistics[]>> {
    const req = this.createRequest('GET', '/statistics');
    const mapped = req.prepareArgs({
      from: [from, string()],
      to: [to, string()],
    });
    req.query('from', mapped.from);
    req.query('to', mapped.to);
    return req.callAsJson(array(statisticsSchema), requestOptions);
  }
}
