/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Attribute {
  id?: number;
  description?: string;
  attribute?: string;
  expression?: string;
  /** String|Number|Boolean */
  type?: string;
}

export const attributeSchema: Schema<Attribute> = object({
  id: ['id', optional(number())],
  description: ['description', optional(string())],
  attribute: ['attribute', optional(string())],
  expression: ['expression', optional(string())],
  type: ['type', optional(string())],
});
