/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Calendar {
  id?: number;
  name?: string;
  /** base64 encoded in iCalendar format */
  data?: string;
  attributes?: unknown;
}

export const calendarSchema: Schema<Calendar> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  data: ['data', optional(string())],
  attributes: ['attributes', optional(unknown())],
});
