/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Command {
  id?: number;
  deviceId?: number;
  description?: string;
  type?: string;
  attributes?: unknown;
}

export const commandSchema: Schema<Command> = object({
  id: ['id', optional(number())],
  deviceId: ['deviceId', optional(number())],
  description: ['description', optional(string())],
  type: ['type', optional(string())],
  attributes: ['attributes', optional(unknown())],
});
