/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CommandType {
  type?: string;
}

export const commandTypeSchema: Schema<CommandType> = object({
  type: ['type', optional(string())],
});
