/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Device {
  id?: number;
  name?: string;
  uniqueId?: string;
  status?: string;
  disabled?: boolean;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  lastUpdate?: string;
  positionId?: number;
  groupId?: number;
  phone?: string;
  model?: string;
  contact?: string;
  category?: string;
  attributes?: unknown;
}

export const deviceSchema: Schema<Device> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  uniqueId: ['uniqueId', optional(string())],
  status: ['status', optional(string())],
  disabled: ['disabled', optional(boolean())],
  lastUpdate: ['lastUpdate', optional(string())],
  positionId: ['positionId', optional(number())],
  groupId: ['groupId', optional(number())],
  phone: ['phone', optional(string())],
  model: ['model', optional(string())],
  contact: ['contact', optional(string())],
  category: ['category', optional(string())],
  attributes: ['attributes', optional(unknown())],
});
