/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema';

export interface DeviceAccumulators {
  deviceId?: number;
  /** in meters */
  totalDistance?: number;
  hours?: number;
}

export const deviceAccumulatorsSchema: Schema<DeviceAccumulators> = object({
  deviceId: ['deviceId', optional(number())],
  totalDistance: ['totalDistance', optional(number())],
  hours: ['hours', optional(number())],
});
