/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Driver {
  id?: number;
  name?: string;
  uniqueId?: string;
  attributes?: unknown;
}

export const driverSchema: Schema<Driver> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  uniqueId: ['uniqueId', optional(string())],
  attributes: ['attributes', optional(unknown())],
});
