/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Event {
  id?: number;
  type?: string;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  eventTime?: string;
  deviceId?: number;
  positionId?: number;
  geofenceId?: number;
  maintenanceId?: number;
  attributes?: unknown;
}

export const eventSchema: Schema<Event> = object({
  id: ['id', optional(number())],
  type: ['type', optional(string())],
  eventTime: ['eventTime', optional(string())],
  deviceId: ['deviceId', optional(number())],
  positionId: ['positionId', optional(number())],
  geofenceId: ['geofenceId', optional(number())],
  maintenanceId: ['maintenanceId', optional(number())],
  attributes: ['attributes', optional(unknown())],
});
