/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Geofence {
  id?: number;
  name?: string;
  description?: string;
  area?: string;
  calendarId?: number;
  attributes?: unknown;
}

export const geofenceSchema: Schema<Geofence> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  description: ['description', optional(string())],
  area: ['area', optional(string())],
  calendarId: ['calendarId', optional(number())],
  attributes: ['attributes', optional(unknown())],
});
