/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Group {
  id?: number;
  name?: string;
  groupId?: number;
  attributes?: unknown;
}

export const groupSchema: Schema<Group> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  groupId: ['groupId', optional(number())],
  attributes: ['attributes', optional(unknown())],
});
