/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string, unknown } from '../schema';

export interface Maintenance {
  id?: number;
  name?: string;
  type?: string;
  start?: number;
  period?: number;
  attributes?: unknown;
}

export const maintenanceSchema: Schema<Maintenance> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  type: ['type', optional(string())],
  start: ['start', optional(number())],
  period: ['period', optional(number())],
  attributes: ['attributes', optional(unknown())],
});
