/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Notification {
  id?: number;
  type?: string;
  always?: boolean;
  web?: boolean;
  mail?: boolean;
  sms?: boolean;
  calendarId?: number;
  attributes?: unknown;
}

export const notificationSchema: Schema<Notification> = object({
  id: ['id', optional(number())],
  type: ['type', optional(string())],
  always: ['always', optional(boolean())],
  web: ['web', optional(boolean())],
  mail: ['mail', optional(boolean())],
  sms: ['sms', optional(boolean())],
  calendarId: ['calendarId', optional(number())],
  attributes: ['attributes', optional(unknown())],
});
