/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PortEnum
 */
export enum PortEnum {
  Enum8082 = '8082',
  Enum80 = '80',
}

/**
 * Schema for PortEnum
 */
export const portEnumSchema: Schema<PortEnum> = stringEnum(PortEnum);
