/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ReportSummary {
  deviceId?: number;
  deviceName?: string;
  /** in knots */
  maxSpeed?: number;
  /** in knots */
  averageSpeed?: number;
  /** in meters */
  distance?: number;
  /** in liters */
  spentFuel?: number;
  engineHours?: number;
}

export const reportSummarySchema: Schema<ReportSummary> = object({
  deviceId: ['deviceId', optional(number())],
  deviceName: ['deviceName', optional(string())],
  maxSpeed: ['maxSpeed', optional(number())],
  averageSpeed: ['averageSpeed', optional(number())],
  distance: ['distance', optional(number())],
  spentFuel: ['spentFuel', optional(number())],
  engineHours: ['engineHours', optional(number())],
});
