/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ReportStops {
  deviceId?: number;
  deviceName?: string;
  duration?: number;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  startTime?: string;
  address?: string;
  lat?: number;
  lon?: number;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  endTime?: string;
  /** in liters */
  spentFuel?: number;
  engineHours?: number;
}

export const reportStopsSchema: Schema<ReportStops> = object({
  deviceId: ['deviceId', optional(number())],
  deviceName: ['deviceName', optional(string())],
  duration: ['duration', optional(number())],
  startTime: ['startTime', optional(string())],
  address: ['address', optional(string())],
  lat: ['lat', optional(number())],
  lon: ['lon', optional(number())],
  endTime: ['endTime', optional(string())],
  spentFuel: ['spentFuel', optional(number())],
  engineHours: ['engineHours', optional(number())],
});
