/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface ReportTrips {
  deviceId?: number;
  deviceName?: string;
  /** in knots */
  maxSpeed?: number;
  /** in knots */
  averageSpeed?: number;
  /** in meters */
  distance?: number;
  /** in liters */
  spentFuel?: number;
  duration?: number;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  startTime?: string;
  startAddress?: string;
  startLat?: number;
  startLon?: number;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  endTime?: string;
  endAddress?: string;
  endLat?: number;
  endLon?: number;
  driverUniqueId?: number;
  driverName?: string;
}

export const reportTripsSchema: Schema<ReportTrips> = object({
  deviceId: ['deviceId', optional(number())],
  deviceName: ['deviceName', optional(string())],
  maxSpeed: ['maxSpeed', optional(number())],
  averageSpeed: ['averageSpeed', optional(number())],
  distance: ['distance', optional(number())],
  spentFuel: ['spentFuel', optional(number())],
  duration: ['duration', optional(number())],
  startTime: ['startTime', optional(string())],
  startAddress: ['startAddress', optional(string())],
  startLat: ['startLat', optional(number())],
  startLon: ['startLon', optional(number())],
  endTime: ['endTime', optional(string())],
  endAddress: ['endAddress', optional(string())],
  endLat: ['endLat', optional(number())],
  endLon: ['endLon', optional(number())],
  driverUniqueId: ['driverUniqueId', optional(number())],
  driverName: ['driverName', optional(string())],
});
