/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface Server {
  id?: number;
  registration?: boolean;
  readonly?: boolean;
  deviceReadonly?: boolean;
  limitCommands?: boolean;
  map?: string;
  bingKey?: string;
  mapUrl?: string;
  poiLayer?: string;
  latitude?: number;
  longitude?: number;
  zoom?: number;
  twelveHourFormat?: boolean;
  version?: string;
  forceSettings?: boolean;
  coordinateFormat?: string;
  openIdEnabled?: boolean;
  openIdForce?: boolean;
  attributes?: unknown;
}

export const serverSchema: Schema<Server> = object({
  id: ['id', optional(number())],
  registration: ['registration', optional(boolean())],
  readonly: ['readonly', optional(boolean())],
  deviceReadonly: ['deviceReadonly', optional(boolean())],
  limitCommands: ['limitCommands', optional(boolean())],
  map: ['map', optional(string())],
  bingKey: ['bingKey', optional(string())],
  mapUrl: ['mapUrl', optional(string())],
  poiLayer: ['poiLayer', optional(string())],
  latitude: ['latitude', optional(number())],
  longitude: ['longitude', optional(number())],
  zoom: ['zoom', optional(number())],
  twelveHourFormat: ['twelveHourFormat', optional(boolean())],
  version: ['version', optional(string())],
  forceSettings: ['forceSettings', optional(boolean())],
  coordinateFormat: ['coordinateFormat', optional(string())],
  openIdEnabled: ['openIdEnabled', optional(boolean())],
  openIdForce: ['openIdForce', optional(boolean())],
  attributes: ['attributes', optional(unknown())],
});
