/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema';

export interface User {
  id?: number;
  name?: string;
  email?: string;
  phone?: string;
  readonly?: boolean;
  administrator?: boolean;
  map?: string;
  latitude?: number;
  longitude?: number;
  zoom?: number;
  password?: string;
  twelveHourFormat?: boolean;
  coordinateFormat?: string;
  disabled?: boolean;
  /** in IS0 8601 format. eg. `1963-11-22T18:30:00Z` */
  expirationTime?: string;
  deviceLimit?: number;
  userLimit?: number;
  deviceReadonly?: boolean;
  limitCommands?: boolean;
  fixedEmail?: boolean;
  poiLayer?: string;
  attributes?: unknown;
}

export const userSchema: Schema<User> = object({
  id: ['id', optional(number())],
  name: ['name', optional(string())],
  email: ['email', optional(string())],
  phone: ['phone', optional(string())],
  readonly: ['readonly', optional(boolean())],
  administrator: ['administrator', optional(boolean())],
  map: ['map', optional(string())],
  latitude: ['latitude', optional(number())],
  longitude: ['longitude', optional(number())],
  zoom: ['zoom', optional(number())],
  password: ['password', optional(string())],
  twelveHourFormat: ['twelveHourFormat', optional(boolean())],
  coordinateFormat: ['coordinateFormat', optional(string())],
  disabled: ['disabled', optional(boolean())],
  expirationTime: ['expirationTime', optional(string())],
  deviceLimit: ['deviceLimit', optional(number())],
  userLimit: ['userLimit', optional(number())],
  deviceReadonly: ['deviceReadonly', optional(boolean())],
  limitCommands: ['limitCommands', optional(boolean())],
  fixedEmail: ['fixedEmail', optional(boolean())],
  poiLayer: ['poiLayer', optional(string())],
  attributes: ['attributes', optional(unknown())],
});
