/**
 * TraccarLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter';
import { PortEnum } from './models/portEnum';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  host: string;
  port: PortEnum;
  basicAuthUserName: string;
  basicAuthPassword: string;
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Environment2 = 'environment2',
  Environment3 = 'environment3',
  Environment4 = 'environment4',
  Environment5 = 'environment5',
  Environment6 = 'environment6',
}
